data_path: ../data/utr_mrl_non_AUG_alldataset.csv
output_dir: ./results/mrl_predictor_noAUG
num_layer: 3
padding: 2
num_targets: 1
seq_length: 50
seq_depth: 4
patience: 3
lr: 0.001 
epochs: 30 
dropout: 0.2 
batch_size: 64 
noAUG: True