num_layer: 6
num_targets: 1
seq_depth: 6
model_name: hl_predictor
checkpoint: ../model_weights/hl_predictor-best.pth
recp_path: ./recp_field/saluki_model_6layer.yaml
data_path: ../data/f0_c0_data0_wholeseq.h5

