seq_length: 12288
seq_depth: 6
num_layers: 6
num_targets: 1
model_name: hl_predictor
checkpoint: ../../model_weights/hl_predictor-best.pth
recp_path: ../recp_field/saluki_model_6layer.yaml 
featuremap_layer_name_dict_path: ../feature_cluster_criteria/saluki_model_6layer.yaml
st_lib: ../../data/human_rbp_microrna_motif.meme
multi_thread: True